version: "3.3"

services:
  mysql:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web-performance
      MYSQL_USER: performance
      MYSQL_PASSWORD: 123456
    volumes:
      # - ./web-performance.sql:/web-performance.sql
      - ./data:/var/lib/mysql
      - ./web-performance.sql:/docker-entrypoint-initdb.d/web-performance.sql
      # - ./build/sql.sh:/docker-entrypoint-initdb.d/sql.sh
    # command: "sh /docker-entrypoint-initdb.d/sql.sh"
    # command: "mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} < /${MYSQL_DATABASE}.sql"
    # command: "mysql -u root -p123456 web-performance < /web-performance.sql"

  web:
    build: .
    restart: unless-stopped
    environment:
      DOMAIN: 127.0.0.1
      HOST: 127.0.0.1
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web-performance
      MYSQL_USER: performance
      MYSQL_PASSWORD: 123456
    ports:
      - 18088:18088
    links:
      - mysql
      